#lang rash

(provide MONOLINGUAL BILINGUAL)

(define MONOLINGUAL
  '(
    "apertium-incubator/apertium-alt/"
    "apertium-incubator/apertium-aze/"
    "apertium-languages/apertium-bak/"
    "apertium-languages/apertium-chv/"
    "apertium-languages/apertium-crh/"
    "apertium-languages/apertium-gag/"
    "apertium-languages/apertium-kaa/"
    "apertium-languages/apertium-kaz/"
    "apertium-languages/apertium-kir/"
    "apertium-incubator/apertium-kjh/"
    "apertium-incubator/apertium-krc/"
    "apertium-languages/apertium-kum/"
    "apertium-languages/apertium-nog/"
    "apertium-incubator/apertium-ota/"
    "apertium-languages/apertium-sah/"
    "apertium-languages/apertium-tat/"
    "apertium-languages/apertium-tuk/"
    "apertium-languages/apertium-tur/"
    "apertium-languages/apertium-tyv/"
    "apertium-languages/apertium-uig/"
    "apertium-languages/apertium-uzb/"))

(define BILINGUAL
  '("apertium-incubator/apertium-chv-tat/"
    "apertium-incubator/apertium-chv-tur/"
    "apertium-trunk/apertium-crh-tur/"
    "apertium-trunk/apertium-eng-kaz/"
    "apertium-incubator/apertium-eo-tr/"
    "apertium-incubator/apertium-fin-kaz/"
    "apertium-incubator/apertium-kaz-kaa/"
    "apertium-nursery/apertium-kaz-kir/"
    "apertium-nursery/apertium-kaz-kum/"
    "apertium-trunk/apertium-kaz-rus/"
    "apertium-incubator/apertium-kaz-sah/"
    "apertium-trunk/apertium-kaz-tat/"
    "apertium-incubator/apertium-kaz-tur/"
    "apertium-incubator/apertium-kaz-tyv/"
    "apertium-incubator/apertium-kaz-uig/"
    "apertium-incubator/apertium-kir-uzb/"
    "apertium-incubator/apertium-ky-en/"
    "apertium-incubator/apertium-nog-kaz/"
    "apertium-incubator/apertium-sah-eng/"
    "apertium-nursery/apertium-tat-bak/"
    "apertium-incubator/apertium-tat-eng/"
    "apertium-incubator/apertium-tat-kaa/"
    "apertium-incubator/apertium-tat-kir/"
    "apertium-nursery/apertium-tat-rus/"
    "apertium-nursery/apertium-tuk-tur/"
    "apertium-nursery/apertium-tur-aze/"
    "apertium-incubator/apertium-tur-fin/"
    "apertium-nursery/apertium-tur-kir/"
    "apertium-nursery/apertium-tur-tat/"
    "apertium-nursery/apertium-tur-uzb/"
    "apertium-incubator/apertium-uig-tur/"
    "apertium-incubator/apertium-uzb-kaa/"))
