#lang racket

(define LEXICALISE-ДАЙ #t)
(define LEXICALISE-ЛЫ #t)
(define LEXICALISE-COMP-VERBS #t)
(define LEXICALISE-CAUS #t)
(define LEXICALISE-REFL #t)

`(
  ("<а ( %- а )*>" INTERJ () () ())
  ("аба" "аба" N1 () () ())
  ("абадан" "абадан" N1 () () ())
  ("абадан" "абадан" A2 () () ())
  ("абажа" "абажа" N1 () ("абажадай") ())
  ,(when LEXICALISE-ДАЙ '("абажадай" "абажадай" A1 () () ()))
  ("абажур" "абажур" N1 () ("абажурлы") ())
  ,(when LEXICALISE-ЛЫ '("абажурлы" "абажурлы" A2 () () ()))
  ("абаз" "абаз" N1 () () ())
  ("абазин" "абазин" N1-NAT () ("абазиндер") ())
  ("абазия" "абазия" N1 () ())
  ("абай" "абай" N1 ("attention") ("абаймен") ())
  ("абай" "абай" A1 ("cautious,attentive,beware") () ())
  ,(when LEXICALISE-COMP-VERBS '("абай% бол" "абай% бол" V-IV () () ()))
  ,(when LEXICALISE-COMP-VERBS '("абай% бер" "абай% бер" V-IV () () ()))
  ("абай% қоқай" "абай% қоқай" N1 () () ())
  ("абайла" "абайла" V-TV () ("абайлан" "абайлау") () ())
  ("абайлағыш" "абайлағыш" A2 () () ())
  ,(when LEXICALISE-REFL '("абайлан" "абайлан" V-TV-REFL () () ("абайла")))
  ("абайлаңқыра" "абайлаңқыра" V-TV-LESS () () ())
  ,(when LEXICALISE-CAUS '("абайлат" "абайлат" V-TV-CAUS () ("абайлату") ("абайла"))))